### ISSUE TITLE
No room code 

### ISSUE THREAD

**Issue by NIMFER** [adrenak/univoice#14]
posted this issue originally on [airsignal](https://github.com/adrenak/airsignal/issues/2), posting it also here just in case.

**Comment by klys** [comment]
I am having the same issue, futher more after the first room, not any other room can be created, not anybody can join.

**Comment by adrenak** [comment]
This could be an issue with the sample app scripts. Samples have been updated recently and was found to work.

Do note that if using the telepathy network implementation, use v1.0.1. 1.0.0 has a bug when more than one peer connected
