### ISSUE TITLE
Sample Scene,where is it ?

### ISSUE THREAD

**Issue by kiranmaya** [adrenak/univoice#19]
Unable to locate sample scene. where is it ,is there any separate sample project which uses both univoice and unimic ?
i saw an entry here "Assets/Adrenak.UniVoice/Samples/Scenes/GroupVoiceCallSample.unity" , but its not found in project.
![Screenshot_4](https://user-images.githubusercontent.com/3712631/204729782-f5a3e7b0-1c0d-49fd-83a7-f1afbbce4b38.jpg)

**Comment by adrenak** [comment]
Hi, samples are in the process of being updated but you can find the existing sample project here https://github.com/adrenak/univoice-sample

**Comment by kiranmaya** [comment]
I have read your scripts, you were using photon pun services in both examples, I'm looking my own custom services ways to do voice chat,
 is it possible for " net code for game objects " networking to do voice chat is does it have network variables and send message concepts built-in, or any other out-of-unity approach using .net  libs?

**Comment by adrenak** [comment]
I haven't used network for GO myself, but generally speaking univoice doesn't care about the network implementation, so it should be possible.

There are limitations that could be enforced by the layer, for example PUN2 throttles your traffic if you send too much custom data too often. You might want to look into that while implementing.

**Comment by adrenak** [comment]
Feel free to reopen but closing for now as this page has the link to the samples and netcode is a separate discussion altogether.
