### ISSUE TITLE
PC build works fine, but Android doesn't

### ISSUE THREAD

**Issue by Arex360** [adrenak/univoice#23]
Its working fine in PC but when I switch to android, it doens't work, after doing debugging using log cat, I got this issue
`2023/10/14 03:20:44.566 21419 21441 Fatal libc Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 21441 (UnityMain), pid 21419 (ngleMultiplayer)
2023/10/14 03:20:44.838 22927 22927 Fatal DEBUG     #13 pc 00387d4f  /data/app/com.DefaultCompany.SingleMultiplayer-9CyCLx7zqtwpt5nFFx0rbg==/lib/arm/libunity.so
`
any idea?

also I get this issue as well
`2023/10/17 20:55:51.424 25214 25234 Error Unity DllNotFoundException: Unable to load DLL 'webrtccsharpwrap'. Tried the load the following dynamic libraries: Unable to load dynamic library 'webrtccsharpwrap' because of 'Failed to open the requested dynamic library (0x06000000) dlerror() = dlopen failed: library "webrtccsharpwrap" not found
`

**Comment by adrenak** [comment]
Hi @Arex360 

Do you get this error as soon as you switch to Android, or do you get it on build time, or at runtime on a phone? 

The webrtc libraries that the sample uses are old and are not IL2CPP compatible. For testing purposes, try shifting to Mono backend. The webrtc layer is due for change which should fix the IL2cpp issues soon.

**Comment by Arex360** [comment]
Yes, after switching to `Mono` it works! 
But, to release game on google play store, according to play store policy, the game must be arm64 compatible as well, in that case, lets wait for `IL2CPP` , hope we get it soon

**Comment by Akravator91** [comment]
Hi @Arex360 what kind of network library do you use. ?

I am still struggling to implement the Univoice with mirror.,
perhaps if you dont mind, can you share your Unity project.? :)

**Comment by Arex360** [comment]
@Akravator91  I am  using AirSignaling, hosted the node js server on my cloud as well

I have noticed, android `Mono` build works but `IL2CPP` doesn't work

**Comment by adrenak** [comment]
Airsignal and Airpeer that uses it, which is turn is used to create the webrtc based network implementation likely needs to be dropped. The last of il2cpp support stems from there

Looks like com.unity.webrtc is a viable solution, it also has samples. I'll explore it this weekend.

Another user of univoice is helping out with mirror support, hopefully in a week or so both will be sorted out!

**Comment by adrenak** [comment]
Mirror support is here: https://github.com/adrenak/univoice-mirror-network
