### ISSUE TITLE
Host on server

### ISSUE THREAD

**Issue by ageekmaster** [adrenak/univoice#28]
hi
how can i set host on the dedicated server build
or how can i change the host when current host leave or disconnect? i need a way to keep connection open whenever host is online or disconnected

**Comment by adrenak** [comment]
Hi @ageekmaster 

Which network implementation are you using? airpeer, telepathy, pun2 or your own?

If you want your dedicated server build to be the host, change your application code such that on a server/headless build you create a room and on a client you join a room.

This link might be helpful: https://noobtuts.com/unity/detect-headless-mode
