### ISSUE TITLE
bug when pressing create room

### ISSUE THREAD

**Issue by jok0436** [adrenak/univoice#4]
NullReferenceException: Object reference not set to an instance of an object
Adrenak.UniVoice.Examples.SimpleApp.Create (UnityEngine.UI.InputField input) (at Assets/Adrenak/UniVoice/Scripts/SimpleApp.cs:75)
UnityEngine.Events.InvokableCall`1[UnityEngine.UI.InputField].Invoke (UnityEngine.UI.InputField args0) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:207)
UnityEngine.Events.CachedInvokableCall`1[UnityEngine.UI.InputField].Invoke (System.Object[] args) (at C:/buildslave/unity/build/Runtime/Export/UnityEvent.cs:345)
UnityEngine.Events.UnityEvent.Invoke () (at C:/buildslave/unity/build/Runtime/Export/UnityEvent_0.cs:70)
UnityEngine.UI.Button.Press () (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:66)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/UI/Core/Button.cs:108)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:50)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor) (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/ExecuteEvents.cs:261)
UnityEngine.EventSystems.EventSystem:Update() (at C:/buildslave/unity/build/Extensions/guisystem/UnityEngine.UI/EventSystem/EventSystem.cs:377)

**Comment by adrenak** [comment]
Hey looks like a bug in the sample scene. maybe a simple missing reference exception. If you've fixed it can you submit a PR?
