### ISSUE TITLE
Cant create a room

### ISSUE THREAD

**Issue by Xogy** [adrenak/UniVoice#5]
Hello sorry to bother I am not sure if I am doing something wrong here, I was following the example. I just cant to connect to any room.

I saw it in know issue that it can fail on mobile data/wifi, but I use cable connection and running it on the computer(might be this the problem?). I Would really appreciate help with my issue because this library really looks awesome and I would love to use it! 

```C#
    public AudioSource audioSource;
    private Voice voice;
    void Start()
    {
        voice = Voice.New(audioSource);
        if (PhotonNetwork.IsMasterClient)
        {
            Debug.Log($"Creating voice chat room: '{NetworkManager.RoomName}'");
            voice.Create(NetworkManager.RoomName, onCreate);
        }
        else
        {
            voice.Join(NetworkManager.RoomName, onConnect);
        }
    }
    
    void onCreate(bool success)
    {
        voice.Join(NetworkManager.RoomName, onConnect);
        Debug.Log($"Create Event {success}");
    }
    void onConnect(bool success)
    {
        voice.Speaking = true;
        Debug.Log($"Connect event {success}");
    }
```

**Comment by adrenak** [comment]
I see, yes there are issues that can come up with firewall, NAT punching and other things. WebRTC is quite complicated and honestly I don't understand it very well myself.

On the other hand, I am now spending more time on my open source, and I may look into this soon. Unity has it's own webrtc library now. I might provide an implementation based on it.
